Sponsors and Team
26samaahmed/fullybeyond pull request #6
Opened 2024-08-06 02:00 UTC by lori33c

2024-08-06 04:32 UTC, 26samaahmed requested changes
Sponsor Section looks good! The Teams section also looks good but there is a problem with some of the images where some are stretched out. Look at photo for reference. I'm not sure if this is the case on my side only.

![Screenshot 2024-08-05 212735](https://github.com/user-attachments/assets/ef329d01-0a68-4b67-9bd8-9e642f494713)

2024-08-06 15:58 UTC, lori33c commented
I fixed the photos and made the font bigger and bolder as well.
![Capture](https://github.com/user-attachments/assets/1df1af44-c17a-4a32-8f74-77f82348ad6e)

2024-08-06 16:12 UTC, lori33c commented
![Capture1](https://github.com/user-attachments/assets/5ed55eda-2916-4949-9ace-c4193c8c28e3)

2024-08-06 17:19 UTC, 26samaahmed commented
Looks really good Lori 👏🏻 I think what's left right now would be making it responsive and adding the rest of the organizers once they fill out the form! We can leave the sponsors empty as is until we have more updates.

2024-08-06 17:47 UTC, 26samaahmed requested changes
Some styling can be translated into Tailwind. I added some changes in the TeamMember.svelte file but you can also try to minimize the use of vanilla css in Team.svelte. Here is a good link where you can search for the specific styling https://tailwindcss.com/docs/flex-basis

2024-08-06 17:47 UTC, 26samaahmed commented on src/components/TeamMember.svelte
> +        <img class="profile-image rounded-full w-52 h-52 z-10 top-0 left-0 transform relative" src={image} alt={name} />
```suggestion
        <img class="border-20 border[##000000] border-solid rounded-full w-52 h-52 z-10 top-0 left-0 transform relative" src={image} alt={name} />
```

2024-08-06 17:47 UTC, 26samaahmed commented on src/components/TeamMember.svelte
> +      border-width: 20px; /* Adjust border width */
```suggestion

```

2024-08-06 17:47 UTC, 26samaahmed commented on src/components/TeamMember.svelte
> +      border-color: black; /* Border color */
```suggestion
```

2024-08-06 17:47 UTC, 26samaahmed commented on src/components/TeamMember.svelte
> +      border-style: solid; /* Border style */
```suggestion
```

2024-08-21 03:39 UTC, ryan-avancena commented
very good and the page is responsive and looks good to go

only suggestion is that we might want to add some other visuals in the background for the blue "meet our team" section (if it's not too late), looks v good tho!

2024-08-24 19:43 UTC, 26samaahmed commented
I re-ordered the our team so its director, leads, then officers are in last name alphabetical order. Look at photo for reference. It looks really good, good job @lori33c !!
![Screenshot 2024-08-24 124137](https://github.com/user-attachments/assets/892457c6-bbd8-4803-82b5-232a49c347fb)

2024-09-01 01:30 UTC, merged